// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg8kqkNvsVtkMgAqCAVl43owZRT5NZ3Yg',
    appId: '1:1016757516301:web:8f7ab3a961ff573f547d44',
    messagingSenderId: '1016757516301',
    projectId: 'taskly-c395b',
    authDomain: 'taskly-c395b.firebaseapp.com',
    storageBucket: 'taskly-c395b.firebasestorage.app',
    measurementId: 'G-XSPDGSVYP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJbtevh1aqhJ0uAiDW_prWbnrHtwpJSAA',
    appId: '1:1016757516301:android:f2c5f0310ffa1e56547d44',
    messagingSenderId: '1016757516301',
    projectId: 'taskly-c395b',
    storageBucket: 'taskly-c395b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7sAZZDXiO1xpbqY2PxUzl3p7t653cEOs',
    appId: '1:1016757516301:ios:771d05f0108526f2547d44',
    messagingSenderId: '1016757516301',
    projectId: 'taskly-c395b',
    storageBucket: 'taskly-c395b.firebasestorage.app',
    iosBundleId: 'com.example.taskly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7sAZZDXiO1xpbqY2PxUzl3p7t653cEOs',
    appId: '1:1016757516301:ios:771d05f0108526f2547d44',
    messagingSenderId: '1016757516301',
    projectId: 'taskly-c395b',
    storageBucket: 'taskly-c395b.firebasestorage.app',
    iosBundleId: 'com.example.taskly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg8kqkNvsVtkMgAqCAVl43owZRT5NZ3Yg',
    appId: '1:1016757516301:web:ac2d00c2f2262ff3547d44',
    messagingSenderId: '1016757516301',
    projectId: 'taskly-c395b',
    authDomain: 'taskly-c395b.firebaseapp.com',
    storageBucket: 'taskly-c395b.firebasestorage.app',
    measurementId: 'G-CDHZTECZT6',
  );
}
