// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuZrHbSGXG1s19Wo9hfs0gWGgctygf5BU',
    appId: '1:800591543684:web:99afbf481999d44dc4b1d1',
    messagingSenderId: '800591543684',
    projectId: 'moglance',
    authDomain: 'moglance.firebaseapp.com',
    storageBucket: 'moglance.firebasestorage.app',
    measurementId: 'G-J86RKJV0BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkbYZ2ZxAAxsL6kJwhZi-RmOspuNsyUzA',
    appId: '1:800591543684:android:3b0487f198d7a2c2c4b1d1',
    messagingSenderId: '800591543684',
    projectId: 'moglance',
    storageBucket: 'moglance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc2U6lwz2M6SDguVaPTcqMKHWWEq2GdLU',
    appId: '1:800591543684:ios:147c38be7a7d524ec4b1d1',
    messagingSenderId: '800591543684',
    projectId: 'moglance',
    storageBucket: 'moglance.firebasestorage.app',
    iosBundleId: 'com.example.taskly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc2U6lwz2M6SDguVaPTcqMKHWWEq2GdLU',
    appId: '1:800591543684:ios:147c38be7a7d524ec4b1d1',
    messagingSenderId: '800591543684',
    projectId: 'moglance',
    storageBucket: 'moglance.firebasestorage.app',
    iosBundleId: 'com.example.taskly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuZrHbSGXG1s19Wo9hfs0gWGgctygf5BU',
    appId: '1:800591543684:web:44a7598eba02a601c4b1d1',
    messagingSenderId: '800591543684',
    projectId: 'moglance',
    authDomain: 'moglance.firebaseapp.com',
    storageBucket: 'moglance.firebasestorage.app',
    measurementId: 'G-PJPG35FW3N',
  );

}